

services:

  graph:
    extends:
      file: docker-compose.yml
      service: graph

  api:
    extends:
      file: docker-compose.yml
      service: api
    environment:
      # Replace the below domain with the domain you want to serve the node API from
      VIRTUAL_HOST: localhost
      VIRTUAL_PATH: ${NB_NAPI_BASE_PATH:-/}
      VIRTUAL_PORT: 8000
      # Set the below to the same domain as VIRTUAL_HOST to enable HTTPS
      LETSENCRYPT_HOST: myservice1.myinstitute.org 

  federation:
   extends:
    file: docker-compose.yml
    service: federation
   environment:
    # Replace the below domain with the domain you want to serve the federation API from
    VIRTUAL_HOST: localhost
    # To change the line below, edit the NB_FAPI_BASE_PATH variable in the .env file
    VIRTUAL_PATH: ${NB_FAPI_BASE_PATH:-/}
    VIRTUAL_PORT: 8000
    # Set the below to the same domain as VIRTUAL_HOST to enable HTTPS
    LETSENCRYPT_HOST: myservice2.myinstitute.org

  query_federation:
    extends:
      file: docker-compose.yml
      service: query_federation
    environment:
      # Replace the below domain with the domain you want to serve the query tool from
      VIRTUAL_HOST: localhost
      VIRTUAL_PATH: ${NB_QUERY_APP_BASE_PATH:-/}
      VIRTUAL_PORT: 5173
      # Set the below to the same domain as VIRTUAL_HOST to enable HTTPS
      LETSENCRYPT_HOST: ${HOST_NAME:-localhost}

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx/reverse_proxy.conf:/etc/nginx/conf.d/reverse_proxy.conf
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro


secrets:
  db_admin_password:
    file: ${NB_GRAPH_SECRETS_PATH:-./secrets}/NB_GRAPH_ADMIN_PASSWORD.txt
  db_user_password:
    file: ${NB_GRAPH_SECRETS_PATH:-./secrets}/NB_GRAPH_PASSWORD.txt

volumes:
  graphdb_home:
  vhost:
  html:
  certs:
  acme: