version: "3.8"

services:
  api:
    image: "neurobagel/api:${NB_API_TAG:-latest}"
    ports:
      - "${NB_API_PORT_HOST:-8000}:${NB_API_PORT:-8000}"
    environment:
      NB_GRAPH_USERNAME: ${NB_GRAPH_USERNAME}
      NB_GRAPH_PASSWORD: ${NB_GRAPH_PASSWORD}
      NB_GRAPH_ADDRESS: ${NB_GRAPH_ADDRESS:-graph}
      NB_GRAPH_PORT: ${NB_GRAPH_PORT:-7200}
      NB_GRAPH_DB: ${NB_GRAPH_DB:-repositories/my_db}
      NB_RETURN_AGG: ${NB_RETURN_AGG:-true}
      NB_API_PORT: ${NB_API_PORT:-8000}
      NB_API_ALLOWED_ORIGINS: ${NB_API_ALLOWED_ORIGINS}
  graph:
    image: "${NB_GRAPH_IMG:-ontotext/graphdb:10.3.1}"
    volumes:
      - "${NB_GRAPH_ROOT_HOST:-~/graphdb-home}:${NB_GRAPH_ROOT_CONT:-/opt/graphdb/home}"
    ports:
      - "${NB_GRAPH_PORT_HOST:-7200}:${NB_GRAPH_PORT:-7200}"