name: Compatibility test

on:
  push:
    branches:
      - cypress
  workflow_dispatch:

jobs:
  Compatibility-test:
    runs-on: ubuntu-latest
        
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Rename files
        working-directory: ./dev
        run: |
          cp template.env .env
          cp local_nb_nodes.template.json local_nb_nodes.json
          sed -i 's/latest/nightly/g' .env
      
      - name: Run docker compose
        working-directory: ./dev
        run: |
          docker compose --profile full_stack up -d

      - name: Set up node env
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Install cypress
        run: npm install

      - name: Run end to end tests
        uses: cypress-io/github-action@v6
        with:
          wait-on: http://localhost:3000
          component: false


