name: e2e test of full stack services

on:
  workflow_dispatch:
  # TODO: Can remove if we don't want it to run every time
  pull_request:

jobs:
  setup:
    uses: neurobagel/recipes/.github/workflows/test_setup.yml@main

  test-latest:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up node env
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Install Cypress
        run: npm install

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          wait-on: http://localhost:3000
          # otherwise, defaults to Electron
          browser: chrome 
